version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout # check out the code in the project directory
      - run: sudo apt install sqlite clang
      - run: cargo build
      - run: ./test.sh